USE [master]
GO

/****** Object:  Database [BusBook]    Script Date: 11/10/2020 1:19:59 PM ******/
CREATE DATABASE [BusBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BusBook', FILENAME = N'F:\sqldata\BusBook.mdf' , SIZE = 70208KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BusBook_log', FILENAME = N'E:\sqldata\BusBook_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BusBook] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BusBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BusBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BusBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BusBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BusBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BusBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [BusBook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BusBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BusBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BusBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BusBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BusBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BusBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BusBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BusBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BusBook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BusBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BusBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BusBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BusBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BusBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BusBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BusBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BusBook] SET RECOVERY FULL 
GO

ALTER DATABASE [BusBook] SET  MULTI_USER 
GO

ALTER DATABASE [BusBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BusBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BusBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BusBook] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BusBook] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BusBook] SET QUERY_STORE = OFF
GO

USE [BusBook]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [BusBook] SET  READ_WRITE 
GO

